// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigaProTrabajoenGrupo.Migrations
{
    [DbContext(typeof(DBSqlSERVERLigaProECU))]
    [Migration("20250501025045_Migracion Inicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.Property<double>("Presupuesto")
                        .HasColumnType("float");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int");

                    b.HasKey("EquipoId");

                    b.HasIndex("ReporteId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.FormularioPartido", b =>
                {
                    b.Property<int>("FormularioPartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormularioPartidoId"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int>("PartidosPerdidos")
                        .HasColumnType("int");

                    b.HasKey("FormularioPartidoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("FormularioPartido");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugadorId"));

                    b.Property<int>("Asistencias")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<int?>("ReporteId")
                        .HasColumnType("int");

                    b.Property<int?>("ReporteId1")
                        .HasColumnType("int");

                    b.Property<int?>("ReporteId2")
                        .HasColumnType("int");

                    b.Property<double>("Sueldo")
                        .HasColumnType("float");

                    b.HasKey("JugadorId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("ReporteId");

                    b.HasIndex("ReporteId1");

                    b.HasIndex("ReporteId2");

                    b.ToTable("Jugador");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.HasKey("ReporteId");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Equipo", b =>
                {
                    b.HasOne("LigaProTrabajoenGrupo.Models.Reporte", null)
                        .WithMany("EquiposConMayorPresupuesto")
                        .HasForeignKey("ReporteId");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.FormularioPartido", b =>
                {
                    b.HasOne("LigaProTrabajoenGrupo.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Jugador", b =>
                {
                    b.HasOne("LigaProTrabajoenGrupo.Models.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LigaProTrabajoenGrupo.Models.Reporte", null)
                        .WithMany("Jugadores")
                        .HasForeignKey("ReporteId");

                    b.HasOne("LigaProTrabajoenGrupo.Models.Reporte", null)
                        .WithMany("JugadoresConMasAsistencias")
                        .HasForeignKey("ReporteId1");

                    b.HasOne("LigaProTrabajoenGrupo.Models.Reporte", null)
                        .WithMany("JugadoresConMasGoles")
                        .HasForeignKey("ReporteId2");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("LigaProTrabajoenGrupo.Models.Reporte", b =>
                {
                    b.Navigation("EquiposConMayorPresupuesto");

                    b.Navigation("Jugadores");

                    b.Navigation("JugadoresConMasAsistencias");

                    b.Navigation("JugadoresConMasGoles");
                });
#pragma warning restore 612, 618
        }
    }
}
